# -*- coding: utf-8 -*-
"""welding_fcn_yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xrIfP1jJu62p0mXo2P_H959dNv6ddpgC

# Welding Defect Detection — FCN + YOLOv8s Pipeline

**Dataset:** The Welding Defect Dataset v2 (Google Drive)
**Sınıflar:** Bad Weld · Good Weld · Defect

**Mimari:**
```
Görüntü
  ├── FCN → Anomali ısı haritası (texture-level anomaly score)
  └── YOLO → Sınıf + Bbox tahmini
       ↓
  FCN prob skoru × YOLO conf → Birleşik ensemble skoru
       ↓
  Final çıktı: Sınıf + Bbox + Ensemble Confidence
```

**Neden anlamlı?**
- FCN: piksel düzeyinde doku anomalisi → YOLO'nun göremediği ince bölgeleri yakalar
- YOLO: nesne düzeyinde sınıflandırma + lokalizasyon
- Ensemble: iki farklı bilgi kaynağı birbirini destekler

> **Önemli:** `Runtime → Change runtime type → A100 GPU` seç.

## 1. Kurulum & GPU Kontrolü
"""

!pip install ultralytics -q

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import cv2
import os
import time
import shutil
import matplotlib.pyplot as plt
from pathlib import Path
from torch.utils.data import Dataset, DataLoader, random_split

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Kullanılan cihaz: {device}')
if device == 'cuda':
    print(f'GPU : {torch.cuda.get_device_name(0)}')
    print(f'VRAM: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB')

"""## 2. Google Drive'dan Dataset Yükle"""

from google.colab import drive
drive.mount('/content/drive')

DATA_ROOT = '/content/drive/MyDrive/archive-12/The Welding Defect Dataset - v2/The Welding Defect Dataset - v2'

# data.yaml path'ini düzelt (Colab için)
import yaml
yaml_path = f'{DATA_ROOT}/data.yaml'
with open(yaml_path) as f:
    cfg = yaml.safe_load(f)

cfg['path'] = DATA_ROOT
cfg['train'] = f'{DATA_ROOT}/train/images'
cfg['val']   = f'{DATA_ROOT}/valid/images'
cfg['test']  = f'{DATA_ROOT}/test/images'

fixed_yaml = f'{DATA_ROOT}/data_fixed.yaml'
with open(fixed_yaml, 'w') as f:
    yaml.dump(cfg, f, default_flow_style=False, allow_unicode=True)

print('Dataset yüklendi.')
print(f'Sınıflar: {cfg["names"]}')
print(f'Train : {len(list(Path(cfg["train"]).glob("*.jpg")))} görüntü')
print(f'Valid : {len(list(Path(cfg["val"]).glob("*.jpg")))} görüntü')
print(f'Test  : {len(list(Path(cfg["test"]).glob("*.jpg")))} görüntü')

"""## 3. FCN Model Tanımı"""

class DoubleConv(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )
    def forward(self, x):
        return self.block(x)


class FCNAnomalyDetector(nn.Module):
    """
    UNet-style FCN — Welding anomaly segmentation.
    Input : (B, 3, H, W)
    Output: (B, 1, H, W) — sigmoid anomaly score map [0,1]
    Yüksek değer = anomalous bölge (Bad Weld / Defect)
    """
    def __init__(self):
        super().__init__()
        self.pool = nn.MaxPool2d(2, 2)
        self.enc1 = DoubleConv(3,   64)
        self.enc2 = DoubleConv(64,  128)
        self.enc3 = DoubleConv(128, 256)
        self.enc4 = DoubleConv(256, 512)
        self.bottleneck = DoubleConv(512, 1024)
        self.up4  = nn.ConvTranspose2d(1024, 512, 2, stride=2)
        self.dec4 = DoubleConv(1024, 512)
        self.up3  = nn.ConvTranspose2d(512, 256, 2, stride=2)
        self.dec3 = DoubleConv(512,  256)
        self.up2  = nn.ConvTranspose2d(256, 128, 2, stride=2)
        self.dec2 = DoubleConv(256,  128)
        self.up1  = nn.ConvTranspose2d(128, 64,  2, stride=2)
        self.dec1 = DoubleConv(128,  64)
        self.out  = nn.Conv2d(64, 1, 1)

    def forward(self, x):
        e1 = self.enc1(x)
        e2 = self.enc2(self.pool(e1))
        e3 = self.enc3(self.pool(e2))
        e4 = self.enc4(self.pool(e3))
        b  = self.bottleneck(self.pool(e4))
        d4 = self.dec4(torch.cat([self.up4(b),  e4], dim=1))
        d3 = self.dec3(torch.cat([self.up3(d4), e3], dim=1))
        d2 = self.dec2(torch.cat([self.up2(d3), e2], dim=1))
        d1 = self.dec1(torch.cat([self.up1(d2), e1], dim=1))
        return torch.sigmoid(self.out(d1))


class DiceLoss(nn.Module):
    """Dice Loss — lokalize bbox mask için"""
    def __init__(self, smooth=1.0):
        super().__init__()
        self.smooth = smooth
    def forward(self, pred, target):
        p, t = pred.view(-1), target.view(-1)
        return 1 - (2*(p*t).sum() + self.smooth) / (p.sum() + t.sum() + self.smooth)


print('FCN modeli tanımlandı.')

"""## 4. FCN Dataset & Eğitim

**Mask stratejisi:** YOLO bbox → binary mask
- `Bad Weld` (cls=0) → mask=1 (anomaly)
- `Defect`   (cls=2) → mask=1 (anomaly)  
- `Good Weld`(cls=1) → mask=0 (normal)

FCN gerçek bbox'larla eğitildiği için lokalize anomali haritası üretir.
"""

class WeldingDefectDataset(Dataset):
    """
    YOLO bbox → binary anomaly mask
    Bad Weld (0) + Defect (2) → mask=1
    Good Weld (1)             → mask=0
    """
    ANOMALY_CLASSES = {0, 2}  # Bad Weld, Defect

    def __init__(self, root, img_size=640, augment=False):
        self.img_size = img_size
        self.augment  = augment
        img_dir = Path(root) / 'images'
        lbl_dir = Path(root) / 'labels'
        self.samples = []
        for p in sorted(img_dir.iterdir()):
            if p.suffix.lower() in ('.jpg', '.jpeg', '.png'):
                lbl = lbl_dir / (p.stem + '.txt')
                if lbl.exists():
                    self.samples.append((str(p), str(lbl)))
        print(f'[Dataset] {len(self.samples)} örnek: {root}')

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, lbl_path = self.samples[idx]
        img = cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB)
        H, W = img.shape[:2]

        mask = np.zeros((H, W), dtype=np.float32)
        with open(lbl_path) as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) < 5: continue
                cls = int(parts[0])
                if cls not in self.ANOMALY_CLASSES: continue
                cx, cy, bw, bh = map(float, parts[1:5])
                x1 = max(0, int((cx - bw/2) * W))
                y1 = max(0, int((cy - bh/2) * H))
                x2 = min(W, int((cx + bw/2) * W))
                y2 = min(H, int((cy + bh/2) * H))
                mask[y1:y2, x1:x2] = 1.0

        img  = cv2.resize(img,  (self.img_size, self.img_size))
        mask = cv2.resize(mask, (self.img_size, self.img_size),
                          interpolation=cv2.INTER_NEAREST)

        if self.augment:
            if np.random.random() > 0.5:
                img  = cv2.flip(img,  1)
                mask = cv2.flip(mask, 1)
            if np.random.random() > 0.5:
                img  = cv2.flip(img,  0)
                mask = cv2.flip(mask, 0)

        img_t  = torch.from_numpy(img.astype(np.float32) / 255.0).permute(2,0,1)
        mask_t = torch.from_numpy(mask).unsqueeze(0)
        return img_t, mask_t


def collate_fn(batch):
    return torch.stack([b[0] for b in batch]), torch.stack([b[1] for b in batch])


def iou_score(pred, target, thr=0.5):
    p = (pred.squeeze() > thr).float()
    t = target.squeeze().float()
    inter = (p * t).sum().item()
    union = (p + t).clamp(0, 1).sum().item()
    return inter / union if union >= 1 else float('nan')


def mean_iou(preds, targets, thr=0.5):
    scores = [iou_score(preds[i], targets[i], thr) for i in range(preds.shape[0])]
    valid  = [s for s in scores if s == s]
    return float(np.mean(valid)) if valid else float('nan')


# ── Hiperparametreler ─────────────────────────────────────────────────────
FCN_IMG_SIZE  = 640
FCN_EPOCHS    = 50
FCN_BATCH     = 16
FCN_LR        = 3e-4
PATIENCE      = 8
MIN_DELTA     = 1e-4
FCN_SAVE_PATH = '/content/fcn_best.pt'
# ─────────────────────────────────────────────────────────────────────────

train_ds = WeldingDefectDataset(f'{DATA_ROOT}/train', img_size=FCN_IMG_SIZE, augment=True)
val_ds   = WeldingDefectDataset(f'{DATA_ROOT}/valid', img_size=FCN_IMG_SIZE, augment=False)

tr_loader = DataLoader(train_ds, batch_size=FCN_BATCH, shuffle=True,  num_workers=4, collate_fn=collate_fn)
vl_loader = DataLoader(val_ds,   batch_size=FCN_BATCH, shuffle=False, num_workers=4, collate_fn=collate_fn)

# Coverage diagnostiği
sample_masks = [train_ds[i][1].numpy() for i in range(min(50, len(train_ds)))]
coverage = float(np.mean([m.mean() for m in sample_masks]))
print(f'Anomaly piksel oranı : {coverage*100:.1f}%')
print(f'Eğitim: {len(train_ds)} | Validasyon: {len(val_ds)}')
print(f'Epoch: {FCN_EPOCHS} | Batch: {FCN_BATCH} | ImgSize: {FCN_IMG_SIZE}\n')

fcn_model = FCNAnomalyDetector().to(device)
criterion = DiceLoss()
optimizer = optim.AdamW(fcn_model.parameters(), lr=FCN_LR, weight_decay=1e-4)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=FCN_EPOCHS)

best_val_loss = float('inf')
best_iou      = 0.0
no_improve    = 0
history       = {'tr_loss': [], 'vl_loss': [], 'tr_iou': [], 'vl_iou': []}

print(f"{'Epoch':>6} {'Tr Loss':>9} {'Tr IoU':>8} {'Vl Loss':>9} {'Vl IoU':>8} {'Süre':>7}")
print('-' * 55)

for epoch in range(1, FCN_EPOCHS + 1):
    t0 = time.time()

    # Train
    fcn_model.train()
    tr_loss, tr_iou_sum, tr_iou_n = 0.0, 0.0, 0
    for imgs, masks in tr_loader:
        imgs, masks = imgs.to(device), masks.to(device)
        optimizer.zero_grad()
        preds = fcn_model(imgs)
        loss  = criterion(preds, masks)
        loss.backward()
        optimizer.step()
        tr_loss += loss.item()
        bi = mean_iou(preds.detach().cpu(), masks.cpu())
        if bi == bi: tr_iou_sum += bi; tr_iou_n += 1

    # Validation
    fcn_model.eval()
    vl_loss, vl_iou_sum, vl_iou_n = 0.0, 0.0, 0
    with torch.no_grad():
        for imgs, masks in vl_loader:
            imgs, masks = imgs.to(device), masks.to(device)
            preds = fcn_model(imgs)
            vl_loss += criterion(preds, masks).item()
            bi = mean_iou(preds.cpu(), masks.cpu())
            if bi == bi: vl_iou_sum += bi; vl_iou_n += 1

    scheduler.step()

    tl = tr_loss    / len(tr_loader)
    ti = tr_iou_sum / max(tr_iou_n, 1)
    vl = vl_loss    / len(vl_loader)
    vi = vl_iou_sum / max(vl_iou_n, 1)
    history['tr_loss'].append(tl); history['tr_iou'].append(ti)
    history['vl_loss'].append(vl); history['vl_iou'].append(vi)

    flag = ''
    if vl < best_val_loss - MIN_DELTA:
        best_val_loss = vl
        best_iou      = vi
        no_improve    = 0
        torch.save(fcn_model.state_dict(), FCN_SAVE_PATH)
        flag = '  ✓ saved'
    else:
        no_improve += 1
        flag = f'  [{no_improve}/{PATIENCE}]'

    print(f"{epoch:>6} {tl:>9.4f} {ti:>8.4f} {vl:>9.4f} {vi:>8.4f} {time.time()-t0:>6.1f}s{flag}")

    if no_improve >= PATIENCE:
        print(f'\n⏹ Early stopping: {PATIENCE} epoch iyileşme yok.')
        break

print(f'\nFCN tamamlandı. Val Loss: {best_val_loss:.4f} | IoU: {best_iou:.4f}')

# FCN eğitim grafikleri
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
ax1.plot(history['tr_loss'], label='Train Loss')
ax1.plot(history['vl_loss'], label='Val Loss')
ax1.set_title('FCN — Dice Loss'); ax1.set_xlabel('Epoch'); ax1.legend(); ax1.grid(True)
ax2.plot(history['tr_iou'], label='Train IoU')
ax2.plot(history['vl_iou'], label='Val IoU')
ax2.set_title('FCN — Foreground IoU'); ax2.set_xlabel('Epoch'); ax2.legend(); ax2.grid(True)
plt.tight_layout()
plt.savefig('/content/fcn_curves.png', dpi=150)
plt.show()

"""## 5. YOLOv8s Eğitimi"""

from ultralytics import YOLO

yolo_model = YOLO('yolov8s.pt')

results = yolo_model.train(
    data=fixed_yaml,
    epochs=300,
    imgsz=640,
    batch=64,
    device=device,
    workers=4,
    patience=20,
    save=True,
    project='/content/runs',
    name='welding_yolov8s',
    optimizer='AdamW',
    lr0=0.001,
    lrf=0.01,
    momentum=0.937,
    weight_decay=0.0005,
    warmup_epochs=3,
    cos_lr=True,
    verbose=True,
)

YOLO_BEST = '/content/runs/welding_yolov8s/weights/best.pt'
print('YOLO eğitimi tamamlandı.')

best_yolo = YOLO(YOLO_BEST)
metrics   = best_yolo.val()
print(f'mAP50    : {metrics.box.map50:.4f}')
print(f'mAP50-95 : {metrics.box.map:.4f}')
print(f'Precision: {metrics.box.mp:.4f}')
print(f'Recall   : {metrics.box.mr:.4f}')

"""## 6. FCN + YOLO Ensemble Pipeline

**Ensemble mantığı:**
- YOLO her bbox için conf ve sınıf üretir
- FCN, bbox bölgesinin ortalama anomaly skorunu üretir
- `ensemble_score = yolo_conf × (1 + α × fcn_score)`
- Good Weld detection'larında FCN skoru düşükse ceza uygulanır
- Bu sayede FCN, YOLO'nun false positive'lerini filtreler
"""

# ── Pipeline sabitleri ────────────────────────────────────────────────────
FCN_THRESHOLD  = 0.4   # Anomaly mask eşiği
YOLO_CONF      = 0.20  # YOLO minimum confidence
YOLO_IOU       = 0.45
ALPHA          = 0.4   # FCN boost katsayısı
FINAL_CONF_THR = 0.18  # Ensemble sonrası minimum skor
ANOMALY_CLS    = {0, 2}  # Bad Weld, Defect
# ─────────────────────────────────────────────────────────────────────────

fcn_model.load_state_dict(torch.load(FCN_SAVE_PATH, map_location=device))
fcn_model.eval()
print('FCN yüklendi.')

yolo_det    = YOLO(YOLO_BEST)
class_names = list(yolo_det.names.values())
print(f'YOLO yüklendi. Sınıflar: {class_names}')


@torch.no_grad()
def fcn_predict(img_bgr):
    """FCN anomaly probability map üret (orijinal boyutta)"""
    H, W = img_bgr.shape[:2]
    rgb  = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    inp  = cv2.resize(rgb, (FCN_IMG_SIZE, FCN_IMG_SIZE))
    t    = torch.from_numpy(inp.astype(np.float32)/255.).permute(2,0,1).unsqueeze(0).to(device)
    prob = fcn_model(t).squeeze().cpu().numpy()
    prob_full   = cv2.resize(prob, (W, H))
    binary_mask = (prob_full > FCN_THRESHOLD).astype(np.uint8) * 255
    return binary_mask, prob_full


def ensemble_pipeline(img_bgr):
    """
    FCN + YOLO Ensemble:
    1. YOLO tüm görüntüde detection yapar
    2. FCN anomaly map üretir
    3. Her detection için bbox bölgesindeki FCN skoru hesaplanır
    4. Anomaly sınıflarında FCN boost, Good Weld'de FCN cezası uygulanır
    5. ensemble_score = yolo_conf × (1 + α × fcn_mean)
    """
    H, W = img_bgr.shape[:2]

    # YOLO
    raw_dets = []
    for r in yolo_det(img_bgr, conf=YOLO_CONF, iou=YOLO_IOU, verbose=False):
        for box in r.boxes:
            bx1,by1,bx2,by2 = map(int, box.xyxy[0].tolist())
            raw_dets.append([bx1,by1,bx2,by2, float(box.conf[0]), int(box.cls[0])])

    # FCN anomaly map
    binary_mask, prob_map = fcn_predict(img_bgr)

    # Ensemble skoru
    final_dets = []
    for bx1,by1,bx2,by2,yolo_conf,cls in raw_dets:
        # Bbox bölgesindeki FCN ortalama anomaly skoru
        bx1c = max(0, bx1); by1c = max(0, by1)
        bx2c = min(W, bx2); by2c = min(H, by2)
        roi_prob = prob_map[by1c:by2c, bx1c:bx2c]
        fcn_mean = float(roi_prob.mean()) if roi_prob.size > 0 else 0.0

        if cls in ANOMALY_CLS:
            # Anomaly sınıfı: FCN yüksekse boost
            ensemble = yolo_conf * (1 + ALPHA * fcn_mean)
        else:
            # Good Weld: FCN yüksekse şüpheli → ceza
            ensemble = yolo_conf * (1 - ALPHA * fcn_mean)

        ensemble = float(np.clip(ensemble, 0, 1))
        if ensemble >= FINAL_CONF_THR:
            final_dets.append((bx1,by1,bx2,by2, yolo_conf, ensemble, cls, fcn_mean))

    return final_dets, binary_mask, prob_map


# Renk: Bad Weld=kırmızı, Good Weld=yeşil, Defect=turuncu
CLS_COLORS = {0: (60,60,255), 1: (60,200,60), 2: (60,165,255)}

def visualize(img_bgr, detections, prob_map):
    out  = img_bgr.copy()
    heat = cv2.applyColorMap((prob_map * 255).astype(np.uint8), cv2.COLORMAP_JET)
    out  = cv2.addWeighted(out, 0.72, heat, 0.28, 0)

    for (bx1,by1,bx2,by2,yolo_conf,ensemble,cls,fcn_mean) in detections:
        color = CLS_COLORS.get(cls, (200,200,200))
        cv2.rectangle(out, (bx1,by1), (bx2,by2), color, 2)
        name  = class_names[cls] if cls < len(class_names) else f'cls{cls}'
        label = f'{name} Y:{yolo_conf:.2f} E:{ensemble:.2f} F:{fcn_mean:.2f}'
        (tw,th),_ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)
        cv2.rectangle(out, (bx1, by1-th-6), (bx1+tw+4, by1), color, -1)
        cv2.putText(out, label, (bx1+2, by1-4),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255,255,255), 1)

    n_anomaly = sum(1 for d in detections if d[6] in ANOMALY_CLS)
    cv2.putText(out, f'Det:{len(detections)} Anomaly:{n_anomaly}',
                (10,32), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255,255,255), 2)
    return out


print('Pipeline hazır.')
print('Label format: Y=YOLO conf | E=Ensemble score | F=FCN anomaly score')

# Test görüntüleri üzerinde pipeline
TEST_DIR    = f'{DATA_ROOT}/test/images'
RESULTS_DIR = '/content/pipeline_results'
os.makedirs(RESULTS_DIR, exist_ok=True)

test_images = [f for f in os.listdir(TEST_DIR)
               if f.lower().endswith(('.jpg','.jpeg','.png'))]
print(f'{len(test_images)} test görüntüsü\n')

total_dets, total_anomaly, times_ms = 0, 0, []

for fname in test_images:
    img = cv2.imread(os.path.join(TEST_DIR, fname))
    t0  = time.time()
    dets, binary_mask, prob_map = ensemble_pipeline(img)
    elapsed = (time.time() - t0) * 1000
    times_ms.append(elapsed)

    n_anomaly = sum(1 for d in dets if d[6] in ANOMALY_CLS)
    total_dets    += len(dets)
    total_anomaly += n_anomaly

    result = visualize(img, dets, prob_map)
    stem   = os.path.splitext(fname)[0]
    cv2.imwrite(f'{RESULTS_DIR}/{stem}_result.jpg',  result)
    cv2.imwrite(f'{RESULTS_DIR}/{stem}_mask.jpg',    binary_mask)

    print(f'{fname:50s} | Det:{len(dets):2d} Anomaly:{n_anomaly} | {elapsed:.0f}ms')

print(f'\n{"="*60}')
print(f'Toplam detection : {total_dets}')
print(f'Anomaly detection: {total_anomaly}')
print(f'Ort. süre        : {np.mean(times_ms):.1f}ms / görüntü')

# İlk 6 sonucu göster
result_files = sorted([f for f in os.listdir(RESULTS_DIR) if f.endswith('_result.jpg')])[:6]
fig, axes = plt.subplots(2, 3, figsize=(18, 10))
for ax, fname in zip(axes.ravel(), result_files):
    img = cv2.cvtColor(cv2.imread(f'{RESULTS_DIR}/{fname}'), cv2.COLOR_BGR2RGB)
    ax.imshow(img); ax.set_title(fname[:40], fontsize=7); ax.axis('off')
for ax in axes.ravel()[len(result_files):]:
    ax.axis('off')
plt.suptitle('FCN + YOLOv8s Ensemble Pipeline — Welding Defect Detection\n'
             'Y=YOLO conf | E=Ensemble score | F=FCN anomaly score', fontsize=11)
plt.tight_layout()
plt.savefig('/content/pipeline_results.png', dpi=150)
plt.show()

"""## 7. Sonuçları Google Drive'a Kaydet"""

DRIVE_OUT = '/content/drive/MyDrive/welding_fcn_yolo_results'
os.makedirs(DRIVE_OUT, exist_ok=True)

shutil.copy(FCN_SAVE_PATH, f'{DRIVE_OUT}/fcn_best.pt')
shutil.copy('/content/fcn_curves.png', DRIVE_OUT)
shutil.copy('/content/pipeline_results.png', DRIVE_OUT)

yolo_src = '/content/runs/welding_yolov8s'
yolo_dst = f'{DRIVE_OUT}/yolo_results'
if os.path.exists(yolo_dst): shutil.rmtree(yolo_dst)
shutil.copytree(yolo_src, yolo_dst)

pipe_dst = f'{DRIVE_OUT}/pipeline_results'
if os.path.exists(pipe_dst): shutil.rmtree(pipe_dst)
shutil.copytree(RESULTS_DIR, pipe_dst)

print(f'Tüm sonuçlar kaydedildi: {DRIVE_OUT}')
print(f'  fcn_best.pt          → FCN ağırlıkları')
print(f'  yolo_results/        → YOLOv8s ağırlıkları + metrikler')
print(f'  pipeline_results/    → Test çıktıları')
print(f'  fcn_curves.png       → Eğitim grafikleri')
print(f'  pipeline_results.png → Örnek sonuçlar')